/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef hadoopdatanode_CONSTANTS_H
#define hadoopdatanode_CONSTANTS_H

#include "hadoopdatanode_types.h"



class hadoopdatanodeConstants {
 public:
  hadoopdatanodeConstants();

};

extern const hadoopdatanodeConstants g_hadoopdatanode_constants;



#endif
